# linux:
# 	echo "Compiling for Linux OS"
# 	GOOS=linux GOARCH=amd64 go build

# build: amx
# 	@./scripts/build.sh

BINARY_NAME=AMX_Support_Apis
.DEFAULT_GOAL:= run

build:
	GOARCH=amd64 GOOS=linux go build -o ./target/${BINARY_NAME}-linux main.go
	GOARCH=amd64 GOOS=darwin go build -o ./target/${BINARY_NAME}-darwin main.go
	GOARCH=amd64 GOOS=windows go build -o ./target/${BINARY_NAME}-windows main.go

run : build
	./target/${BINARY_NAME}-darwin

clean :
	go clean
	rm ./target/${BINARY_NAME}-darwin
	rm ./target/${BINARY_NAME}-linux
	rm ./target/${BINARY_NAME}-windows

